def show_menu():
    print("\n" + "=" * 40)
    print("   CHUONG TRINH QUAN LY SINH VIEN")
    print("=" * 40)
    print("1. Them sinh vien")
    print("2. Hien thi toan bo sinh vien")
    print("3. Tim sinh vien theo ma")
    print("4. Tim sinh vien theo ten")
    print("5. Cap nhat sinh vien")
    print("6. Xoa sinh vien")
    print("7. Sap xep GPA tang dan")
    print("8. Sap xep GPA giam dan")
    print("9. Sap xep ten A-Z")
    print("0. Thoat")
    print("=" * 40)
